databaseConfig:
  hostname: 127.0.0.1
  username: backup6m
  password: "*******"
  dbName: rainbowdb

bucketDirName: path/to/bucket

gzip: true

uploadToS3: false
uploadToServer: true

sshServer:
  hostname: uXXX968.your-storagebox.de
  username: uXXX968-sub1
  password: LvtuR6A1F3OXXXXX
  port: 23
